"""
Django settings for dj_blog project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%7&gfs!u_s4ci@5o2*j6tv^$*ju_2ds7-83o#$s#423(4+y4ds'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 添加apps
    'apps.blog_article',
    'apps.blog_console',
    'apps.blog_index',
    'apps.blog_sign',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'dj_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 使用media文件夹
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'dj_blog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blog_django',
        'HOST': '106.14.1.9',
        'PORT': 3306,
        'USER': 'liduo',
        'PASSWORD': '624695549'
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 使用中文

TIME_ZONE = 'Asia/Shanghai'  # 设定时区

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
# 添加静态文件路径
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'statics')

# 设置media文件夹url
MEDIA_URL = '/media/'
# 添加media文件夹
MEDIA_DIR = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = MEDIA_DIR
####################################################
# 自定义User模型类设置
# 继承重写User模型类时，指定自定义的模型类，'app名字.类名'
AUTH_USER_MODEL = 'blog_sign.User'
####################################################
# login_required装饰器设置
# 配置登录界面，供登录验证装饰器login_required使用
LOGIN_URL = '/sign/login'
####################################################
# 邮件设置
# 发送邮件配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 使用ssl加密方式
EMAIL_USE_SSL = True
# smpt服务地址
EMAIL_HOST = 'smtp.163.com'
# 使用ssl的smtp端口465，非ssl端口25
EMAIL_PORT = 465
# 发送邮件的邮箱
EMAIL_HOST_USER = 'liduo945@163.com'
# 在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'liduo945163'
# 收件人看到的发件人
EMAIL_FROM = 'LeeBlog<liduo945@163.com>'
####################################################
# Redis缓存设置
# Django的缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:624695549@106.14.1.9:6379/9",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 配置session存储
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
####################################################
# FastDFS分布式文件存储系统设置
# 设置Django的文件存储类
DEFAULT_FILE_STORAGE = 'utils.fdfs.storage.FDFSStorage'

# 设置fdfs使用的client.conf文件路径
FDFS_CLIENT_CONF = os.path.join(BASE_DIR, 'dj_blog/client.conf')

# 设置fdfs存储服务器上nginx的IP和端口号
FDFS_URL = 'http://106.14.1.9/'
####################################################
